include: package:flutter_lints/flutter.yaml
analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore

  exclude:
    - "*/.g.dart"
    - "*/.freezed.dart"


linter:
  rules:
    prefer_relative_imports: true
    avoid_print: false