// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM1ng5fSC5WZOlH1YvfP3tAfY_388ELB0',
    appId: '1:1016671928495:android:2075a3d4ddc68c6b71145a',
    messagingSenderId: '1016671928495',
    projectId: 'bref-news',
    storageBucket: 'bref-news.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbPeSo5Hw0n3ZGvvnMY6y_tWuLWhdw93I',
    appId: '1:1016671928495:ios:cedf05345c19df4471145a',
    messagingSenderId: '1016671928495',
    projectId: 'bref-news',
    storageBucket: 'bref-news.firebasestorage.app',
    androidClientId: '1016671928495-ou4jc127ee5u2sphtpminh4058hh5v2m.apps.googleusercontent.com',
    iosClientId: '1016671928495-hvm538ksqe6cb9vdvk6mkd4qas0do9ur.apps.googleusercontent.com',
    iosBundleId: 'com.nandak.brefnews',
  );

}